### ISSUE TITLE
Multi-line selection with Shift+up or down arrow not working properly

### ISSUE THREAD

**Issue by kumarve** [marktext/marktext#1167]
### Description

The multi-line selection is not working unless one of the chars is selected fire before pressing Shift+up arrow or Shift + down

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. Type a multiline text say
```
This is a sample content 1
This is a sample content 2
```
2. Keep the cursor before the "This is a sample content 1"
3. Press Shift+Up arrow or Shift+Low arrow

**Expected behavior:**
Content is selected from the position of the cursor and Up or Down lines based on key combination is chosen 

**Actual behavior:**

Direct Shift+Uparrow or Shift+Uparrow doesn't select the content. At least one character has to be selected then do Shift+Uparrow or Shift+Uparrow for multiline to do a select.

- Mark Text:0.14.0
- Operating system: 10.12.6

**Comment by fxha** [comment]
This isuue is already fixed on our latest development version. Thank you for taking the time to report this issue.

**Comment by lkrms** [comment]
Unfortunately this issue is still present (on macOS, at least) in 0.15.1. When a selection is started (a) from the keyboard and (b) within a list, Shift+Down does not expand the selection to the next line. Outside of lists, this issue does not occur.

**Comment by fxha** [comment]
@Illyism Could you please explain your issue in detail because we cannot reproduce it, neither on v0.15.1 nor develop.
