### ISSUE TITLE
Certain link syntax does not work

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1450]
### Description

Mark Text handle an internet link like this:
`[own text](https://en.wikipedia.org/wiki/Kingdom_of_Israel_(united_monarchy)#Civil_war)`

it is rendered like this
`own text#Civil_war)`

and point+click does not take you to the right page.

- [x] Can you reproduce the issue? 

### Steps to reproduce

Try the example above.

**Expected behavior:**

the #Civil_war) bit should be included in the link, so that the rendered text only shows `own text` underlined.

**Actual behavior:**

As described above.

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15.0
- Operating system: Linux Mint 19.2

**Comment by fxha** [comment]
@DutchPete The issue is already fixed, thanks for reporting it.

**Comment by DutchPete** [comment]
@fxha Felix, I just downloaded version 0.15.1 and opened the same file, but the bug is still there.

**Comment by Jocs** [comment]
@DutchPete This issue has been fixed on develop branch, and will be released in version 0.16.0.

**Comment by DutchPete** [comment]
@Jocs OK, thanks for letting me know that.

**Comment by DutchPete** [comment]
One last comment that may be useful for you:

when I export to PDF the file in which that buggy link occurs, the link in PDF occurs normal AND it opens the correct web page in the browser !
