### ISSUE TITLE
your system does not have picgo installed, please install it before use.

### ISSUE THREAD

**Issue by liwmj** [marktext/marktext#3118]
****
### Description

- 1.The environment variable
![image](https://user-images.githubusercontent.com/2976366/157796619-05046cae-114a-41c1-b429-e8ca0a3d6ebd.png)

- 2.Upload clipboard pictures
![image](https://user-images.githubusercontent.com/2976366/157796719-80aabed7-acf5-4a16-b0b6-88b2808c4279.png)

I really don't know where the problem is, help!

### Steps to reproduce

- "Preferences"->"Image"->"Uploader", select "picgo", prompt "your system does not have picgo installed, please install it before use."
- Has always been, Even when you reboot your computer.

### Versions

- MarkText version:0.17.1
- Operating system:macOS Monterey 12.2.1

**Comment by YalandHong** [comment]
Duplicate of #2996. But I prefer this issue since it uses English and contains a screenshot.

**Comment by liwmj** [comment]
> Duplicate of #2996. But I prefer this issue since it uses English and contains a screenshot.

I just checked #2996 and it's slightly different from my environment, My Picgo is a command line application(The exact expression is picgo-core), while #2996 is a desktop application.

In addition, I tried picgo's desktop program on my computer, and it still failed.

**Comment by shPisces** [comment]
my Marktext is 0.17.1，and Picgo is 2.3.0. It has a error:
![image](https://user-images.githubusercontent.com/41283993/158584077-bd614582-6fb1-42ff-9d4b-efaea5a7aa7e.png)
![image](https://user-images.githubusercontent.com/41283993/158584200-71870b21-13ef-4acc-8e88-5b8b34475424.png)
![image](https://user-images.githubusercontent.com/41283993/158584280-79e9d419-e8de-40ff-b3b5-c2e5b8714820.png)

**Comment by JoJoJotarou** [comment]
I successfully uploaded the image using [Picgo-core](https://github.com/PicGo/PicGo-Core)

install & setting
```bash
npm install picgo -g
picgo add gitee
picgo set uploader
```

Then i manually changed the values of  `uploader` and `current` to `gitee`(Their default `smms`, and can not changed by `picgo set uploader`. I not known why🥲).This is my config.json.
```json
// ~/.picgo/config.json
{
  "picBed": {
    "uploader": "gitee",
    "current": "gitee",
    "gitee": {
      "owner": "xxx",
      "repo": "xxx",
      "path": "xxx",
      "token": "xxx",
      "message": ""
    }
  },
  "picgoPlugins": {
    "picgo-plugin-gitee": true
  }
}
```
OS: Windows11
nodejs: v16.14.0
marktext: 0.17.1
picgo-core: 1.5.0-alpha.0

**Comment by daoshenzzg** [comment]
我用`Shell script location`解决了....

1. 第一步：安装[PicGo-Core](https://picgo.github.io/PicGo-Core-Doc/zh/guide/)。我是mac，命令我用的`npm install picgo -g`，可能会遇到一些错误，按照提示修复即可。
2. 第二步：[sm.sm](https://sm.ms/login)官网注册个账号，登录后再个人主页找到`API Token`菜单，点击`Generate Secret Token`按钮，生成一个`Secret Token`。
3. 第三步：把上一步的token，配置到picgo配置文件去，参考[PicGo-Core](https://picgo.github.io/PicGo-Core-Doc/zh/guide/)配置。json文件加一个：
```json
"smms": {
      "token": "$YOUR_TOKEN" // 从 https://sm.ms/home/apitoken 获取的 token
    }
```
4. 第四步：通过`picgo u xxx.png` 上传一个图片试试效果。
5. 准备一个sh脚本，比如我的`picgo_upload.sh`，并给执行权限，如`chmod 755 picgo_upload.sh`
```bash
#!/bin/bash
source  /etc/profile
export LANG="en_US.UTF-8"

img="$(~/.npm-global/bin/picgo u $1)"
echo $img | awk '{print $NF}' 
```
6. MarkText>Preferences>Image>Upload image to cloud xxxx>Command line script。然后再Shell script location处，填写刚刚的脚本绝对路径，并保存。
<img width="950" alt="image" src="https://user-images.githubusercontent.com/7531802/158986282-d69ba675-82c4-4941-82a9-592e3a64919a.png">
7. 效果测试
上传中...
<img width="532" alt="image" src="https://user-images.githubusercontent.com/7531802/158986381-a739f105-793d-4405-8b83-62292375476b.png">
上传成功：
<img width="585" alt="image" src="https://user-images.githubusercontent.com/7531802/158986791-f16af328-59f5-4be8-97cf-90949b4e208a.png">

**Comment by fxha** [comment]
We had/have a similar issues with pandoc on macOS. Is MarkText somehow isolated on the OS?

**Comment by liwmj** [comment]
In my opinion, Mark Text runs on a native MAC OS.

Installation：```brew install marktext```
Operation:：```Launchpad --> click 'MarkText'```

> We had/have a similar issues with pandoc on macOS. Is MarkText somehow isolated on the OS?

**Comment by hjue** [comment]
> @daoshenzzg 我也配置命令行脚本，但是不成功，手动单独执行可以，感觉marktext并没有调用配置的脚本，也没有其他异常信息

我也是同样的情况。不知道在哪里可以看到marktext的日志

**Comment by nanbobike** [comment]
need the function  "choose  the picgo  install   location"

**Comment by daoshenzzg** [comment]
> @daoshenzzg 我也配置命令行脚本，但是不成功，手动单独执行可以，感觉marktext并没有调用配置的脚本，也没有其他异常信息

我试了下，我的这种方式，拷贝的本地图片没有问题，截图的不行。

**Comment by tianfeng98** [comment]
@daoshenzzg 
`picgo`上传截图只需要使用`picgo u`
![image](https://user-images.githubusercontent.com/37977609/172651354-32173deb-6ea7-4209-8d93-807c6f643493.png)
我在源码中做了如下修改可以实现上传截图：
![image](https://user-images.githubusercontent.com/37977609/172652050-554d9dd9-c986-445f-a39d-199fe9af78d8.png)
![image](https://user-images.githubusercontent.com/37977609/172652260-4fbb070e-c1d1-4653-8a07-c7c16dfc5db9.png)
对于`picgo`的上传我认为可以单独写一个方法，不用和`cliScript`耦合在一起。

**Comment by coderwing** [comment]
> @daoshenzzg `
找到了，修改marktext重新打包

**Comment by coderwing** [comment]
可以修改一下脚本：

``` shell
#!/bin/bash
source  /etc/profile
export LANG="en_US.UTF-8"
img="$(/usr/local/bin/picgo u $1)"
echo $img | awk '{print "![]("$NF")"}' | pbcopy
```
将上传后的url组装成markdown 图片url放到剪切板中。

截图后配合一个串门上传文件的命令行窗口

**Comment by tianfeng98** [comment]
我在Windows 10上实验，`npm i -g picgo`安装`picgo-core`之后，就可以正常检测到picgo命令并执行。
但MacOS上有一个奇怪的现象：
启动dev命令是可以检测到picgo并正常使用
<img width="683" alt="image" src="https://user-images.githubusercontent.com/37977609/173106027-0b4d564f-cad1-408c-ba68-aa26fe82a021.png">
使用build命令打包后，安装`.dmg`包，发现picgo命令又失效了
<img width="657" alt="image" src="https://user-images.githubusercontent.com/37977609/173106282-2573c3e3-c6d0-4edc-b201-4e609d290ee7.png">
picgo的子进程命令似乎没有执行……

MacOS: Monterey 12.4

**Comment by coderwing** [comment]
> 

您好，我修改了代码，重新编译打包后，打开的app上传图片还是只能上传复制的本地路径的图片，截图的还是不行，我都已经修改成这样了：
<img width="778" alt="image" src="https://user-images.githubusercontent.com/49760271/173308648-c7fbd7bd-b2a5-4eff-a32a-641f8afd6f21.png">

**Comment by stutiredboy** [comment]
不能正常处理截图，只能是已经保存在本地的文件可以用自定义脚本的方式，这就有点尴尬

**Comment by chinayangxiaowei** [comment]
Modify here and add the path "/usr/local/bin"
```javascript
const patchEnvPath = () => {
  if (process.platform === 'darwin') {
    process.env.PATH += (process.env.PATH.endsWith(path.delimiter) ? '' : path.delimiter) +
    '/usr/local/bin:/Library/TeX/texbin'
  }
}
```

**Comment by cyy53589** [comment]
> Modify here and add the path "/usr/local/bin"
> 
> ```js
> const patchEnvPath = () => {
>   if (process.platform === 'darwin') {
>     process.env.PATH += (process.env.PATH.endsWith(path.delimiter) ? '' : path.delimiter) +
>     '/usr/local/bin:/Library/TeX/texbin'
>   }
> }
> ```

@chinayangxiaowei 
It seems that my '/usr/local/bin' folder dose not contain PicGo. Are you using PicGo Core?

**Comment by chinayangxiaowei** [comment]
> > Modify here and add the path "/usr/local/bin"
> > ```js
> > const patchEnvPath = () => {
> >   if (process.platform === 'darwin') {
> >     process.env.PATH += (process.env.PATH.endsWith(path.delimiter) ? '' : path.delimiter) +
> >     '/usr/local/bin:/Library/TeX/texbin'
> >   }
> > }
> > ```
> 
> @chinayangxiaowei It seems that my '/usr/local/bin' folder dose not contain PicGo. Are you using PicGo Core?

Yes, I'm using the picgo command line version of "picgo core".
You can install it by typing "npm install -g picgo" in the terminal console

**Comment by Thesoul20** [comment]
There is a long time since the first discuss, but the problem still appear in the last version of MarkText. I hope the maintainers will resolve this bug:

1. MarkText can find the  system picgo-core application.
2. the images in the clipboard will upload normally through picgo.

**Comment by Admingyu** [comment]
same problem here, not working event write a bash.

**Comment by jt-z** [comment]
same problem here，no matter what , thanks for the all developers!

**Comment by Admingyu** [comment]
for any one may run into this problem, i made a fix version at [https://github.com/Admingyu/marktext/releases/tag/v0.0.1](https://github.com/Admingyu/marktext/releases/tag/v0.0.1)

changes:[here](https://github.com/Admingyu/marktext/commit/3a4e2b4d9d8354faeb1dbc72fb8be11d25fe659a)

**Comment by dodiadodia** [comment]
I rebuild marktext and release a fixed version on MacOS [picgo-core installed by brew](https://github.com/dodiadodia/marktext/releases/tag/v0.17.1)
Fixed:
1. Can't find picgo-core cmdline
2. Can't upload the images in the clipboard
 Welcome to try.

**Comment by Xnhyacinth** [comment]
> I rebuild marktext and release a fixed version on MacOS [picgo-core installed by brew](https://github.com/dodiadodia/marktext/releases/tag/v0.17.1) Fixed:
> 
> 1. Can't find picgo-core cmdline
> 2. Can't upload the images in the clipboard
>    Welcome to try.

I'm using macos and marktext version is 0.17.1. I still can't detect the picgo installed!

**Comment by Jocs** [comment]
Thanks for the detailed report and screenshots, and thanks to everyone who shared workarounds in the thread. The root cause was the classic macOS issue where a GUI app launched from Finder/Launchpad doesn't inherit your shell PATH, so MarkText couldn't see the `picgo`/`picgo-core` CLI installed via npm or Homebrew — plus the uploader didn't handle pasted/screenshot images.

Both problems have since been fixed in the current code:
- picgo detection now probes the common install locations on macOS (`/usr/local/bin`, `/opt/homebrew/bin`, `~/.npm-global/bin`, `~/.npm/bin`, `/usr/local/lib/node_modules/.bin`) in addition to PATH, and the app augments PATH at startup (`env.ts`).
- The uploader resolves the picgo binary across those same paths and runs it with an augmented PATH, and clipboard/screenshot images are now written to a temp file and uploaded (not just local file paths).

Given this, I'm closing the issue as resolved. If you still hit "picgo not installed" or clipboard uploads failing on a recent build, please open a new issue with your MarkText version, how picgo was installed, and the output of `which picgo` — happy to dig in. Thanks again!
