### ISSUE TITLE
Doesn't update when modified externally

### ISSUE THREAD

**Issue by anishmittal2020** [marktext/marktext#656]
When the opened markdown file is modified externally (using other text editors) then the file doesn't reload in Marktext.

**Comment by Jocs** [comment]
Yes, we have not implemented this function. If there are more users coming up with the same requirements, we will consider implementing it.

**Comment by TomFrankly** [comment]
This would be a great feature to have, since people may have the same document open within Mark Text on two computers and syncing via Dropbox/Google Drive. If the app detected a file change due to a sync, updating it within Mark Text would be very helpful and would prevent potential loss of work.

**Comment by esm7** [comment]
This is the single critical issue that's preventing me from switching to Mark Text as my daily notes app!
I edit notes from several sources and sync them via GDrive. In my quick attempt to use Mark Text instead of my current app, I unintentionally lost some edits from my phone because Mark Text didn't update :(
Auto-update, either by default or a setting, would be extremely useful.

**Comment by lostpebble** [comment]
Yep, this is huge. I use WebStorm as my main IDE and often make quick edits to the markdown there. Switching back to Mark Text should check the file and update it (or at least show a dialog) - it would be horrible to unknowingly overwrite a bunch of changes made externally.

**Comment by Jocs** [comment]
@esm7 Thank you for your suggestion, we will consider supporting this feature in the next version.

**Comment by Jocs** [comment]
fixed by #796 , so this issue to be closed.

**Comment by salopst** [comment]
>  Jocs moved this from Review to Done in v0.14.0 on Mar 27, 2019

Issue remains in marktext v. 0.15.1 on MacOS Catalina 10.15.3

**Comment by alexaHS-nyc** [comment]
not sure if this is still being maintained as a product, but i have this issue, and in the world of agents editing files, this is a really important feature for me
