### ISSUE TITLE
Wrong position of cursor when delete inline math or ruby raw html

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#897]
### Description

Wrong cursor position when delete `inline math` or `raw ruby element` use <kbd>Backspace</kbd>

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. write foo $a \ne b$
2. put cursor after the second $
3. press backspace to delete the second $.

**Expected behavior:**

foo $a \ne b<cursor>

**Actual behavior:**

foo<cursor> $a \ne b$

**Link to an example: [optional]**

### Versions

- Mark Text: pre-release
- Operating system: All

**Comment by fxha** [comment]
@Jocs  I cannot reproduce this issue. If this should be fixed by #896, please close this issue.

**Comment by Jocs** [comment]
This problem also existed before, but it was impossible to reproduce because it was not fixed #892.
